### PR TITLE
Added Windows location

### PR DESCRIPTION
**Pull request by bxvcd-732**

### CODE REVIEW

**Review by spoutn1k — COMMENTED** [review]
For now, only [Ubuntu on Windows](https://ubuntu.com/tutorials/ubuntu-on-windows#1-overview) is supported. Did you try using `%appdata%` with it ? Can it understand it ? I was under the impression an absolute path was needed as `C:` is accessible in `/mnt` as a mounted drive.

**Comment by bxvcd-732** [comment]
I haven't used Ubuntu, even on Windows so I am not sure. I just mean pure Windows.

**Review by spoutn1k — APPROVED** [review]

**Review by bxvcd-732 — COMMENTED** [review]
ooh you are a genius

**Comment by spoutn1k** [comment]
Detailed the absolute path. Merging.

**Pull request merged**
