### PR TITLE
Add the ability to render MystCraft ages

### PR DESCRIPTION
**Pull request by andrewminer**
Add the ability to render ages created by the [MystCraft](http://www.minecraftforum.net/topic/918541-151-mystcraft-0102/) mod.  This adds a "-mystcraftage _n_" option which specifies the age to be rendered.  It processes that parameter much the same way the "-nether" and "-end" parameters are handled.

### CODE REVIEW

**Comment by Veovis-Muaddib** [comment]
If this goes through I'll be able to point users here when they ask for mapping utilities that support Mystcraft.  Good luck!

**Comment by andrewminer** [comment]
Just checking on status... anything I should fix or change before this gets merged in?  Thanks!

**Comment by Zahl** [comment]
Although mcmap currently isn't up to date I'm gonna merge that, code looks clean. :)

**Comment by fodermester** [comment]
If you try to create a map bigger than -100, -100, 100, 100 the output.png file is corrupt. All images in the cache are readable. -99, -99, 99, 99 and smaller works fine.

 I think you should test the program with some larger maps...

**Pull request merged**
